#!/usr/bin/env bash
# Script that transfers a file from our client to a server
# Ex ./0-transfer_file some_page.html 8.8.8.8 sylvain /vagrant/private_key

if [ "$#" -ne 4 ]; then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
   scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi