#!/usr/bin/env bash
# configures a new Ubuntu machine
# Install nginx on web-01 server

sudo apt update
sudo apt -y install nginx
sudo chown -R "$USER":"$USER"  /var/www/html
sudo chown -R "$USER":"$USER"  /etc/nginx/sites-available/
sudo service nginx start
echo "Holberton School" > /var/www/html/index.nginx-debian.html
new_string="\\\n\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=3MbaGJN2ioQ;\n\t}\n"
check_exist=$(grep "redirect_me" /etc/nginx/sites-available/default)
if [[ -z $check_exist ]];
then
    sed -i "42i $new_string" /etc/nginx/sites-available/default
    sudo service ngnix restart
fi

