#!/usr/bin/env bash
# configures a new Ubuntu machine
# Install nginx on web-01 server

sudo apt update
sudo apt -y install nginx
sudo chown -R "$USER":"$USER"  /var/www/html
sudo chown -R "$USER":"$USER"  /etc/nginx/sites-available/
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
new="_;\n\n\trewrite \/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;\n\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sed -i "s/_;/$new/" /etc/nginx/sites-available/default
sudo service nginx restart
