#!/usr/bin/env bash
#Install nginx on your servers
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
FILE="/etc/nginx/nginx.conf"
sudo sed -i "15i \\\tadd_header X-Served-By $HOSTNAME;" $FILE
sudo service nginx restart
sudo service nginx reload
