#!/usr/bin/env bash
# Install load balancer

sudo apt update
sudo apt install -y haproxy=1.6.\*
setup="
frontend firstbalance
    bind *:80
mode http
default_backend webservers
backend webservers
balance roundrobin
server 2120-web-01 34.75.15.109:80 check
server 2120-web-02 35.227.52.42:80 check
"
echo "$setup" >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy
service haproxy start