#!/usr/bin/env bash
# Script that displays numbers from 1 to 100.


i=1
while [ $i -lt 21 ]
do
    if [ $((i % 15)) -eq 0 ];
    then
	echo "FizzBuzz"
    elif [ $((i % 3)) -eq 0 ];
    then
	echo "Fizz"
    elif [ $((i % 5)) -eq 0 ];
    then
	echo "Buzz"
    else
	echo "$i"
    fi
    ((i++))
done
