#!/usr/bin/env bash
# Script that displays the content of the file /etc/passwd.
# Your script should only display:
# * username
# * user id
# * Home directory path for the user

while read -r line;
do
    echo "$line" | cut -d':' -f 1,4,7
    done < /etc/passwd
