#!/usr/bin/env bash
# Displays Holberton School 10 times using while,
# but for the 9th iteration, displays Holberton School and then Hi on a new line

i=0
while ((i < 10))
do
    if [ $i -eq 9 ]
    then
	echo "Hi"
    fi
    echo "Holberton School"

    ((i++))
done
