#!/usr/bin/env bash
# Script that displays the time for 12 hours and 59 minutes:
# * display hours from 0 to 12
# * display minutes from 1 to 59

hours=0
minutes=1
while ((hours < 13))
do
    echo "Hour: $hours"
    while ((minutes < 60))
    do
	echo $minutes
	((minutes++))
    done
    minutes=1
    ((hours++))
done
