#!/usr/bin/env bash
# Script that fix this container so that Nginx is running as the nginx user.

pkill apache2
chmod 644 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
